AWSTemplateFormatVersion: "2010-09-09"
Description: "Automated SES domain verification and DKIM setup for a specified domain in ap-southeast-2."

Parameters:
  DomainName:
    Type: String
    Description: "The domain name to verify with SES (e.g., subdomain.domain.gov.au)."
  MailFromDomainName:
    Type: String
    Description: "This needs to be a subdomain of !Ref DomainName"
  Route53ZoneId:
    Type: String
    Description: "The Hosted Zone ID for your domain in Route 53."

Resources:
  # Create the SES Domain Identity
  # This resource verifies domain ownership and automatically generates the DKIM tokens.
  SESDomainIdentity:
    Type: AWS::SES::EmailIdentity
    Properties:
      ConfigurationSetAttributes: 
        ConfigurationSetName: !Ref SESMailConfigurationSet
      EmailIdentity: !Ref DomainName
      DkimSigningAttributes:
        NextSigningKeyLength: "RSA_2048_BIT"
      MailFromAttributes:
        MailFromDomain: !Ref MailFromDomainName
      Tags:
        - Key: "environment"
          Value: "poc"
        - Key: "deployment"
          Value: "manual"

  SESMailManagerTrafficPolicy:
    Type: AWS::SES::MailManagerTrafficPolicy
    Properties:
      TrafficPolicyName: DENY-Policy
      DefaultAction: DENY
      PolicyStatements:
        - Action: DENY
          Conditions:
            - IpExpression:
                Evaluate:
                  Attribute:
                    SENDER_IP
                Operator: NOT_CIDR_MATCHES
                Values:
                  - "127.0.0.1/32"

  SESMailManagerRuleSet:
    Type: AWS::SES::MailManagerRuleSet
    Properties:
      RuleSetName: RuleSetNumber1
      Rules:
        - Actions:
            - Archive:
                ActionFailurePolicy: CONTINUE
                TargetArchive: !GetAtt SESMailManagerArchive.ArchiveId

  SESMailManagerArchive:
    Type: AWS::SES::MailManagerArchive
    Properties:
      ArchiveName: !Join ['-', ['sentEmail', !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]]]
      Retention:
         RetentionPeriod: "THREE_MONTHS"

  SESMailConfigurationSet:
    Type: AWS::SES::ConfigurationSet
    Properties:
       Name: ConfigSet1

  SESMailReceiptRuleSet:
     Type: AWS::SES::ReceiptRuleSet
     Properties:
       RuleSetName: default-rule-set


#  # DNS CNAME records for DKIM
#  # This resource creates three CNAME records using the DKIM tokens.
#  SESDKIMRecords:
#    Type: AWS::Route53::RecordSetGroup
#    Properties:
#      HostedZoneId: !Ref Route53ZoneId
#      RecordSets:
#        - Name: !GetAtt SESDomainIdentity.DkimDNSTokenName1
#          Type: CNAME
#          TTL: "60"
#          ResourceRecords:
#            - !GetAtt SESDomainIdentity.DkimDNSTokenValue1
#        - Name: !GetAtt SESDomainIdentity.DkimDNSTokenName2
#          Type: CNAME
#          TTL: "60"
#          ResourceRecords:
#            - !GetAtt SESDomainIdentity.DkimDNSTokenValue2
#        - Name: !GetAtt SESDomainIdentity.DkimDNSTokenName3
#          Type: CNAME
#          TTL: "60"
#          ResourceRecords:
#            - !GetAtt SESDomainIdentity.DkimDNSTokenValue3
#        - Name: !Sub "_dmarc.${DomainName}"
#          Type: TXT
#          TTL: "60"
#          ResourceRecords:
#             - '"v=DMARC1; p=none;"'
#        - Name: !Sub "${MailFromDomainName}"
#          Type: TXT
#          TTL: "60"
#          ResourceRecords:
#             - '"v=spf1 include:amazonses.com ~all"'
#        - Name: !Sub "${MailFromDomainName}"
#          Type: MX
#          TTL: "60"
#          ResourceRecords:
#             - "10 feedback-smtp.ap-southeast-2.amazonses.com"
